### ISSUE TITLE
Whitelist link broken.

### ISSUE THREAD

**Issue by Gibbsdavidl** [pachterlab/MBGBLHGP_2019#1]
Whitelist link appears to be broken.

wget https://github.com/pachterlab/kallistobuspaper_2019/releases/download/getting_started/10xv2_whitelist.txt

--2019-06-18 13:48:49-- https://github.com/pachterlab/kallistobuspaper_2019/releases/download/getting_started/10xv2_whitelist.txt
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/pachterlab/MBGBLHGP_2019/releases/download/getting_started/10xv2_whitelist.txt [following]
--2019-06-18 13:48:49-- https://github.com/pachterlab/MBGBLHGP_2019/releases/download/getting_started/10xv2_whitelist.txt
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2019-06-18 13:48:49 ERROR 404: Not Found.

**Comment by sbooeshaghi** [comment]
Hey! On which page is this link displayed?

I will resolve this momentarily..

**Comment by sbooeshaghi** [comment]
Ah whoops, I found it. Its on the extended explanation page. I will fix this momentarily.

**Comment by sbooeshaghi** [comment]
Everything should be fixed. I will close this issue. If something arises again, feel free to open it back up.

**Comment by Gibbsdavidl** [comment]
Thank you!  :-)
