### ISSUE TITLE
Kallisto to Seurat workflow

### ISSUE THREAD

**Issue by whelena** [pachterlab/MBGBLHGP_2019#2]
Hi I am a beginner in the field and I am looking to use your pipeline for scRNA seq datasets. I went through the kallisto and bustools pipeline and are having trouble uploading the gene matrix to R. I have previously used scater and seurat, so I am wondering is the kallisto output files (.mtx and 2 .txt files) are compatible for downstream analysis in scater/seurat and if so how.

**Comment by lakigigar** [comment]
Please see this tutorial for parsing BUS files in R:

https://bustools.github.io/BUS_notebooks_R/10xv3.html <https://bustools.github.io/BUS_notebooks_R/10xv3.html>

Also https://bustools.github.io/BUS_notebooks_R/10xv2.html <https://bustools.github.io/BUS_notebooks_R/10xv2.html> (for a complete analysis within R).

**Comment by lambdamoses** [comment]
Yes, there is a function called `read_count_output` in the [`BUSpaRse`](https://github.com/BUStools/BUSpaRse) R package that directly reads `bustools` outputs into R as a `dgCMatrix` with barcodes in columns and genes in rows. However, you still need to remove empty droplets from that matrix.

**Comment by whelena** [comment]
Thanks!
