### ISSUE TITLE
GSE118614 download and kb processing

### ISSUE THREAD

**Issue by JBreunig** [pachterlab/MBGBLHGP_2019#3]
Thanks for all of the great tools and tutorials!

Might you have posted the code for the GSE118614 retina sample downloads and pre-processing?  I found the notebook for the GSE118614 processing post KB tools (supp_figure_9.ipynb) but dug through the git and didn't see the pre-processing steps--but found them most of the other samples.

**Comment by atong01** [comment]
Also very interested in this. Unclear what or how to get from the fastq files to the post processed data on this dataset from the kallisto tutorials on the example datasets.
